### ISSUE TITLE
Password leak

### ISSUE THREAD

**Issue by nashe** [vaibhavjain-in/citest#1]
Hi,

I noticed that your password is in clear in the `.travis.yml` file. This can be avoid by using the `travis` gem, with the `travis encrypt` function.
I think that the best things would be to delete this repository and **change your password** (since publicly available Github commit database exists).

**Comment by vaibhavjain-in** [comment]
Thanks guys. Never thought of this.

On Sat, Aug 8, 2015 at 11:07 PM, Thomas Chauchefoin <
notifications@github.com> wrote:

> Hi,
>
> I noticed that your password is in clear in the .travis.yml file. This
> can be avoid by using the travis gem, with the travis encrypt function.
> I think that the best things would be to delete this repository and *change
> your password* (since publicly available Github commit database exists).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vaibhavjain-in/citest/issues/1>.
>



-- 
Regards,
Vaibhav Jain

**Comment by nashe** [comment]
The password can be still found in the commits history and it seems you didn't changed it :(
